# Generated by Django 3.2.9 on 2022-01-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20220128_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='body',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='created_on',
        ),
    ]
