# Generated by Django 3.2.9 on 2022-01-28 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_auto_20220128_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='recive_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfriendschats', to=settings.AUTH_USER_MODEL),
        ),
    ]
