# Generated by Django 3.2.9 on 2022-01-28 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_chats_recive_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='recive_user',
            new_name='from_user',
        ),
        migrations.AddField(
            model_name='chats',
            name='receive_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfriendschatsrecivier', to=settings.AUTH_USER_MODEL),
        ),
    ]
