# Generated by Django 3.2.9 on 2022-01-29 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0005_auto_20220128_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='user_chats',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='from_user',
        ),
        migrations.AddField(
            model_name='chats',
            name='from_user',
            field=models.ManyToManyField(related_name='fromuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chats',
            name='receive_user',
        ),
        migrations.AddField(
            model_name='chats',
            name='receive_user',
            field=models.ManyToManyField(related_name='reciveuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
