# Generated by Django 3.2.9 on 2022-01-29 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0006_auto_20220129_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='receive_user',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='from_user',
        ),
        migrations.AddField(
            model_name='chats',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciveuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
