# Generated by Django 3.2.9 on 2022-01-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20220129_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='recive_user',
            new_name='recive_users',
        ),
    ]
