# Generated by Django 3.2.9 on 2022-01-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_rename_recive_user_chats_recive_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='recive_users',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='from_user',
        ),
    ]
