# Generated by Django 3.2.9 on 2022-02-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_auto_20220129_2036'),
        ('social', '0009_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chats.chats'),
        ),
    ]
