# Generated by Django 3.2 on 2022-09-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_time_chats', '0005_threads_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads',
            name='last_message',
        ),
    ]
